name: Call Reusable Workflow
on:
  push:
    branches:
      - main 
  workflow_dispatch:
  
jobs:
  invoke-reusable-workflow:
    uses: ./.github/workflows/reusable-build.yml  # Call the reusable workflow
    with:
      var1: 'Good boy'
      var2: true
 
